# Generated by Django 4.2.3 on 2023-07-20 18:12

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('datejoined', models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 7, 20, 23, 12, 21, 336180))),
                ('username', models.CharField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(8)])),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(max_length=100)),
                ('age', models.IntegerField(null=True)),
            ],
        ),
    ]
