# Generated by Django 4.2.3 on 2023-07-22 13:25

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='datejoined',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 7, 22, 18, 25, 25, 476491)),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
